type undefinedNumber = undefined | number
export interface FactorInfoType {
    customer_income_average: undefinedNumber,
factor_amount_average : undefinedNumber,
factor_amount_product_average : undefinedNumber,
factor_commisions : undefinedNumber,
factor_product_average : undefinedNumber,
factor_product_count : undefinedNumber,
factor_product_weight : undefinedNumber,
factor_rows_average : undefinedNumber,
gross_new_users : undefinedNumber,
gross_rejected : undefinedNumber,
gross_sale : undefinedNumber,
gross_sale_per_country : {labels: [], data: []}
gross_sale_per_customer_gender : {labels: [], data: []}
gross_sale_per_product_brand : {labels: [], data: []}
gross_sale_per_product_category : {labels: [], data: []}
gross_sale_per_sales_channel : {labels: [], data: []}
new_users_count : undefinedNumber,
old_users_count : undefinedNumber,
percent_rejected_amount : undefinedNumber,
percent_rejected_count : undefinedNumber,
percent_users : undefinedNumber,
pure_factor_counts : undefinedNumber,
pure_gross_sale : undefinedNumber,
pure_product_count : undefinedNumber,
pure_product_weight : undefinedNumber,
pure_sale : undefinedNumber,
rejected_factor_count : undefinedNumber,
rejected_product_count : undefinedNumber,
rejedted_product_weight : undefinedNumber,
sale_factor_count : undefinedNumber,
sum_discount : undefinedNumber,
users_count : undefinedNumber,
}
export interface ProductInfoType {
    customer_income_average : undefinedNumber,
    factor_amount_average : undefinedNumber,
    factor_amount_product_average : undefinedNumber,
    factor_commisions : undefinedNumber,
    factor_product_average : undefinedNumber,
    factor_product_count : undefinedNumber,
    factor_product_weight : undefinedNumber,
    factor_rows_average  : undefinedNumber,
    gross_new_users : undefinedNumber,
    gross_rejected : undefinedNumber,
    gross_sale : undefinedNumber,
    new_users_count : undefinedNumber,
    old_users_count : undefinedNumber,
    percent_rejected_amount : undefinedNumber,
    percent_rejected_count : undefinedNumber,
    percent_users : undefinedNumber,
    pure_factor_counts : undefinedNumber,
    pure_gross_sale : undefinedNumber,
    pure_product_count : undefinedNumber,
    pure_product_weight : undefinedNumber,
    pure_sale : undefinedNumber,
    rejected_factor_count : undefinedNumber,
    rejected_product_count : undefinedNumber,
    rejedted_product_weight : undefinedNumber,
    sale_factor_count : undefinedNumber,
    sum_discount : undefinedNumber,
    users_count : undefinedNumber,
}
